### ISSUE TITLE
Non-function value encountered for default slot. Prefer function slots for better performance.

### ISSUE THREAD

**Issue by XiaoYong1995** [yupk/vue3-code-generator#5]
F12控制台报错“Non-function value encountered for default slot. Prefer function slots for better performance.”
这个能解决吗....

**Comment by XiaoYong1995** [comment]
@yupk 希望大佬可以看看能否解决这个提示.

**Comment by yupk** [comment]
> @yupk 希望大佬可以看看能否解决这个提示.
正在重新写，等等吧

**Comment by XiaoYong1995** [comment]
谢谢大佬

**Comment by yuanjinyong** [comment]
支持大佬，我也在等Vue3版本的。
